version: '3.8'

services:
  backend:
    build:
      context: ./voiceconfirm-backend
    container_name: voiceconfirm-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: ./voiceconfirm-frontend
    container_name: voiceconfirm-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
